### ISSUE TITLE
baseUrl in config file example in README

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/find-it#2]
The example port for the baseUrl is "4567." It might be helpful to have this as "8089" instead, and/or say that it's the same port as in the ArchivesSpace authentication request. (I will admit that I changed the port in my config file to "4567" to match the example.)

**Comment by helrond** [comment]
referenced wrong issue in bf56592533d70710b29a0fc8bf86c1220b890f5c
